export const MOVE_POINT = "MOVE_POINT"
export const SET_DRAGGED_POINT = "SET_DRAGGED_POINT"
export const STOP_DRAGGING = "STOP_DRAGGING"
export const DISABLE_FOCUSSED = "DISABLE_FOCUSSED"
export const SET_FOCUSSED = "SET_FOCUSSED"
export const SET_DRAGGED_QUADRATIC_CONTROL_POINT = "SET_DRAGGED_QUADRATIC_CONTROL_POINT"
export const SET_DRAGGED_CUBIC_CONTROL_POINT = "SET_DRAGGED_CUBIC_CONTROL_POINT"
export const SET_DRAGGED_ARC_CONTROL_POINT = "SET_DRAGGED_ARC_CONTROL_POINT"

export const SET_EDIT_POINT = "SET_EDIT_POINT"
export const SET_EDIT_QUADRATIC_CONTROL_POINT = "SET_EDIT_QUADRATIC_CONTROL_POINT"
export const SET_EDIT_CUBIC_CONTROL_POINT = 'SET_EDIT_CUBIC_CONTROL_POINT'
export const STOP_EDIT = "STOP_EDIT"

export const ANIMATE = "ANIMATE"
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const REWIND = 'REWIND'
export const CLICKED_GEOMETRY = 'CLICKED_GEOMETRY'
export const HOVERED_GEOMETRY = 'HOVERED_GEOMETRY'

export const INPUT_SET_VALUE = 'INPUT_SET_VALUE'