export const UPDATE_KEYS_PRESSED = "UPDATE_KEYS_PRESSED"

export const MOVE_POINT = "MOVE_POINT"
export const SET_DRAGGED_POINT = "SET_DRAGGED_POINT"
export const STOP_DRAGGING = "STOP_DRAGGING"
export const DISABLE_FOCUSSED = "DISABLE_FOCUSSED"
export const SET_FOCUSSED = "SET_FOCUSSED"
export const SET_DRAGGED_QUADRATIC_CONTROL_POINT = "SET_DRAGGED_QUADRATIC_CONTROL_POINT"
export const SET_DRAGGED_CUBIC_CONTROL_POINT = "SET_DRAGGED_CUBIC_CONTROL_POINT"
export const SET_DRAGGED_ARC_CONTROL_POINT = "SET_DRAGGED_ARC_CONTROL_POINT"

export const START_SELECTION = "START_SELECTION"
export const SELECT_BOX = "SELECT_BOX"
export const ADD_TO_SELECTION = "ADD_TO_SELECTION"
export const REMOVE_FROM_SELECTION = "REMOVE_FROM_SELECTION"
export const MOVE_SELECTION = "MOVE_SELECTION"
export const RESET_SELECTION = "RESET_SELECTION"

export const ANIMATE = "ANIMATE"
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const REWIND = 'REWIND'
export const SET_FRAME = 'SET_FRAME'
export const CLICKED_GEOMETRY = 'CLICKED_GEOMETRY'
export const HOVERED_GEOMETRY = 'HOVERED_GEOMETRY'

export const INPUT_SET_VALUE = 'INPUT_SET_VALUE'